<?xml version="1.0"?>
<!DOCTYPE xml>
<!--suppress XmlWrongRootElement -->
<project name="BlightedMC" default="Build">
    <target name="Build">
        <copy file="./blighted-smp/target/blighted-smp-1.0-SNAPSHOT.jar"
              tofile="/Users/moussax/Developer/Minecraft/Server/plugins/${ant.project.name}.jar"
              overwrite="true"
        />
    </target>
</project>
