name: BlightedMC
version: '1.0-SNAPSHOT'
main: fr.moussax.blightedMC.BlightedMC
api-version: '1.21'
authors: [ MrInspection ]

commands:
  broadcast:
    description: Broadcast a message to the server
    aliases:
      - bc
  spawncustommob:
    description: Spawn a BlightedMC creature
    aliases:
      - scm
  test:
    description: General testing command
  gems:
    description: Manage the gems currency system
  craft:
    description: Open the BlightedMC custom crafting table
  loop:
    description: Bulk execute a specific command
  forcecommand:
    description: Force another player to execute a command
  kaboom:
    description: Launch all players or a specific player into the sky
  giveitem:
    description: Open or give yourself a custom item
  god:
    description: Toggle god mode for yourself or another player
  tpall:
    description: Teleport all players to you
  tppos:
    description: Teleport to a position
  fly:
    description: Toggle fly mode for yourself or another player
  forge:
    description: Forge command
  altar:
    description: Altar command
  mod:
    description: Toggle moderation mode or broadcast a message as a moderator with arguments
  mtp:
    description: Teleport to a target. Toggles Moderator Focus
  mtphere:
    description: Moderator command
  endersee:
    description: Moderator command
  invsee:
    description: Moderator command
  kick:
    description: Moderator command
  vanish:
    description: Moderator command
  mute:
    description: Moderator command
  unmute:
    description: Moderator command
  ban:
    description: Moderator command
  banip:
    description: Moderator command
  unban:
    description: Moderator command
  unbanip:
    description: Moderator command