name: BlightedMC
version: '1.0-SNAPSHOT'
main: fr.moussax.blightedMC.BlightedMC
api-version: '1.21'
authors: [ MrInspection ]

commands:
  broadcast:
    description: Broadcast a message to the server
  spawncustommob:
    description: Spawn a BlightedMC creature
  test:
    description: General testing command
  favors:
    description: Manage the Favors currency system
  laser:
    description: BlightedMC test command for lazer ability
  craft:
    description: Open the BlightedMC custom crafting table
  loop:
    description: Execute multiple times a command
  forcecommand:
    description: Force another player to execute a command
  kaboom:
    description: Launch all players or a specific player into the sky
  giveitem:
    description: Open or give yourself a custom item