name: BlightedMC
version: '1.0-SNAPSHOT'
main: fr.moussax.blightedMC.BlightedMC
api-version: '1.21'
authors: [ MrInspection ]

commands:
  broadcast:
    description: Broadcast a message to the server
  spawncustommob:
    description: Spawn a BlightedMC creature
  test:
    description: General testing command
  gems:
    description: Manage the gems currency system
  laser:
    description: BlightedMC test command for lazer ability
  craft:
    description: Open the BlightedMC custom crafting table
  loop:
    description: Execute multiple times a command
  forcecommand:
    description: Force another player to execute a command
  kaboom:
    description: Launch all players or a specific player into the sky
  giveitem:
    description: Open or give yourself a custom item
  god:
    description: Toggle god mode for yourself or another player
  tp:
    description: Teleport to a player or location
  tphere:
    description: Teleport another player to you
  tpall:
    description: Teleport all players to you
  tppos:
    description: Teleport to a position
  fly:
    description: Toggle fly mode for yourself or another player